### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by Lichtsinnig** [rajezvelse/json-server-jwt#1]
Hello, thanks for the microservice that you developed.
Tell me how to properly fill the user base?
`
{
  "users": [
    {
      "id": 1,
      "username": "admin",
      "password": "admin",
      "email": "admin@example.com"
    }
  ],
  "roles": [rw],
  "password_reset_tokens": [],
  "user_settings": []
},
{
  "users": [
    {
      "id": 2,
      "username": "admin2",
      "password": "admin2",
      "email": "admin2@example.com"
    }
  ],
  "roles": [r],
  "password_reset_tokens": [],
  "user_settings": []
}'
one way or the other?

**Comment by rajezvelse** [comment]
@Lichtsinnig  you can add new users using the endpoint `[POST] /users`
